### PR TITLE
🐛 (engine) Load factions only after bidding

### LINKED ISSUE #97: Potential balanced variants issues
> Firaxs wisdom income not working properly on the balanced version
> https://www.boardgamers.space/game/Quick-ground-6142
> i should hv get 3 wisdom, but instead i got +2
> its a huge difference, i cant get a dumb, where i need it, (i had 1 wisdom after turn 1)
> so i should hv had 4 instead of 3
> ....
> and another game
> where my friend could not use bescods passive in a 3p balanced game
> https://www.boardgamers.space/game/Swift-farm-7018

### PR DESCRIPTION
**Pull request by Zevenberge**
Fixes #97 

The faction variant is stored and loaded from the json. This will cause changes in the balanced set to be pinned for the whole game. However, when bidding, the faction can change owner. This caused the wrong variant to load.

### CODE REVIEW

File: engine/src/player.ts [hunk 1]
```diff
@@ -161,12 +161,18 @@ export default class Player extends EventEmitter {
...
     const player = new Player(data.player);
-    player.factionVariant = data.factionVariant;
 
-    if (data.faction) {
-      player.loadFaction(data.faction, customization, expansions, true);
+    const isFactionSelected =
+      phase !== Phase.SetupInit &&
+      phase !== Phase.SetupBoard &&
+      phase !== Phase.SetupFaction &&
+      phase !== Phase.SetupAuction;
```
Comment (coyotte508) [inline engine/src/player.ts:171]: I think you can just test `if (data.board)` to know if a faction has been loaded

File: engine/src/player.ts [hunk 2]
```diff
@@ -339,10 +345,9 @@ export default class Player extends EventEmitter {
     return this.data.occupied.filter((hex) => hex.data.planet !== Planet.Empty && hex.isMainOccupier(this.player));
   }
 
-  loadFaction(faction: Faction, customization: FactionCustomization, expansions = 0, skipIncome = false) {
-    this.faction = faction;
-    this.factionVariant = this.factionVariant ?? factionVariantBoard(customization, faction);
-    this.board = factionBoard(faction, this.factionVariant);
+  loadFaction(customization: FactionCustomization, expansions = 0, skipIncome = false) {
```
Comment (coyotte508) [inline engine/src/player.ts:348]: I like the change

File: engine/src/player.ts (hunk 1 above)
Comment (coyotte508) [reply engine/src/player.ts:171]: Actually it's not exported in the json - my bad.

Exporting `factionLoaded` boolean based on `!!data.board` would be a solution - but it breaks compatibility -- unless we pass the engine version to `fromData`.

I still prefer this latter solution - it's less susceptible to regressions, the `Player` doesn't have to know the flow of the engine, and adding an additional phase at setup won't cause issues.

Comment (Zevenberge) [reply engine/src/player.ts:171]: Alright, sounds good! I'm all in favor of trying to separate those concerns. I will look at that tomorrow.

Comment (Zevenberge) [reply engine/src/player.ts]: Hmz. Apparently just moving the line `this.factionVariant = data.factionVariant` into the `if` statement fixes it. It will unload the faction variant when saving between bids. It feels really hacky to just leave it at that though, as the engine/player then depends on how it is used. So I still went with the suggestion of the `factionLoaded`.
